language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=16

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra

before_install:
  - yes | sdkmanager "platforms;android-27"